name: Release

on:
  push:
    paths:
    - 'Dockerfile'

  workflow_dispatch:

jobs:
  push_image:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v2

      - name: Extract git metadata for image tags
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/octarect/nvim-lspservers
          flavor: latest=true
          tags: type=sha,prefix=

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
