name: Test

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run: |
          # Install Neovim
          mkdir -p build
          wget https://github.com/neovim/neovim/releases/download/v0.5.1/nvim.appimage
          chmod +x nvim.appimage
          mv nvim.appimage ./build/nvim
          echo "${PWD}/build" >> $GITHUB_PATH

          # Download plugins
          mkdir -p ~/.local/share/nvim/site/pack/vendor/start
          git clone https://github.com/nvim-lua/plenary.nvim.git ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim
          git clone https://github.com/neovim/nvim-lspconfig ~/.local/share/nvim/site/pack/vendor/start/nvim-lspconfig

          # Install bundler
          sudo apt install -y --no-install-recommends ruby ruby-dev
          sudo gem install bundler

          # Install erlang
          sudo apt install -y erlang-base erlang-asn1 erlang-public-key erlang-ssl erlang-inets erlang-eunit erlang-dev erlang-parsetools
          sudo curl -L https://github.com/erlang/rebar3/releases/download/3.13.3/rebar3 -o /usr/local/bin/rebar3
          sudo chmod +x /usr/local/bin/rebar3
      - name: Run tests
        run: |
          TEST_DIR=./tests
          nvim --headless -u $TEST_DIR/minimal_init.vim \
            -c "PlenaryBustedDirectory $TEST_DIR { minimal_init = '$TEST_DIR/minimal_init.vim' }" \
            -c q
          ./scripts/test_all_installers.sh

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run: |
          # brew
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

          # Install Neovim
          brew install neovim

          # Download plugins
          mkdir -p ~/.local/share/nvim/site/pack/vendor/start
          git clone https://github.com/nvim-lua/plenary.nvim.git ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim
          git clone https://github.com/neovim/nvim-lspconfig ~/.local/share/nvim/site/pack/vendor/start/nvim-lspconfig

          # Install erlang
          brew install erlang
          brew install rebar3
      - name: Run tests
        run: |
          TEST_DIR=./tests
          nvim --headless -u $TEST_DIR/minimal_init.vim \
            -c "PlenaryBustedDirectory $TEST_DIR { minimal_init = '$TEST_DIR/minimal_init.vim' }" \
            -c q
          ./scripts/test_all_installers.sh

  stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --color always --check .
